apiVersion: v1
kind: Pod
metadata:
  name: mycalc
  labels:
    tier: frontend
spec:
  containers:
  - image: harsh1111/node-web-app:1.1.1
    imagePullPolicy: Never
    name: nodewebapp
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  